#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: azure-dns-config
  namespace: cert-manager
stringData:
  clientSecret: #@ data.values.azure.credentials.aad_client_secret
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-contour-cluster-issuer
spec:
  acme:
    email: #@ data.values.acme.email
    privateKeySecretRef:
      name: acme-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          azureDNS:
            clientID: #@ data.values.azure.credentials.aad_client_id
            clientSecretSecretRef:
              name: azure-dns-config
              key: clientSecret
            subscriptionID: #@ data.values.azure.subscription_id
            tenantID: #@ data.values.azure.tenant_id
            resourceGroupName: #@ data.values.azure.resource_group
            hostedZoneName: #@ data.values.ingress.domain
            environment: AzurePublicCloud
